---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Install nova in Ubuntu
    apt:
      name:
        - nova-compute
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
